name: Android Beta Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./android

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Gradle build action
        uses: gradle/actions/setup-gradle@v5

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE_BASE64 }}
        run: |
          echo $ENCODED_KEYSTORE > keystore_base64.txt
          base64 -d keystore_base64.txt > ${{ runner.temp }}/keystore.jks

      - name: Build Beta APK
        env:
          DECODED_KEYSTORE_PATH: ${{ runner.temp }}/keystore.jks
          RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_STORE_PASSWORD }}
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
          REAPER_API_KEY: ${{ secrets.REAPER_API_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_SENTRY_AUTH_TOKEN }}
          SENTRY_DISTRIBUTION_AUTH_TOKEN: ${{ secrets.SENTRY_DISTRIBUTION_AUTH_TOKEN }}
        run: ./gradlew :app:assembleBeta

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          path: ./android/app/build/outputs/apk/beta/app-beta.apk
          name: hackernews-beta-${{github.sha}}.apk
          if-no-files-found: error
